### ISSUE TITLE
Initialize Frontend

### ISSUE THREAD

**Issue by cj6046** [auburnonlinecs/reviews-fe#1]
# Overview

We have decided to create a React SPA for our frontend. This will then consume our API. There is some initialization that must be done to create a working repository.

# Requirements

**R1:** The React app has been initialized and there is a robust, extensible directory structure

**R2:** There is a template for a .gitignore file

**R3:** The application compiles and serves the React logo page on a local port

**Comment by Brobb954** [comment]
Initialized frontend and merged
