### ISSUE TITLE
Create First Pages

### ISSUE THREAD

**Issue by cj6046** [auburnonlinecs/reviews-fe#3]
### Background

We will need to create the pages which will support our application. These can grow or change over time, but this should give us runway to work and offer a solid MVP of the site.

### Detail

So far, the list of pages we know we want are:
- Home page
- Course detail page

We want these as components which are exported and routable.

### Requirements

**R1:** The home page component is created

**R2:** The course detail page is created

**Comment by cj6046** [comment]
@Brobb954 I think we can move this one to done with the work you've now merged into dev, what do you think?

**Comment by Brobb954** [comment]
Makes sense to me
